---
- name: Prueba
  hosts: windows
  become: true
  
  task:
  - name: Show hostname
    debug:
      ansible_become: true
      msg: "Hostname: {{ ansible_hostname }} "
  - name: run the setup facts
    ansible.builtin.setup:
        
