---
- hosts: windows
  name: Prueba
  become: true
  gather_facts: false
  
  tasks:
    - name: Show hostname
      debug:
        gather_facts: false
        msg: "Hostname: {{ ansible_hostname }} "
        
    - name: run the setup facts
      ansible.builtin.setup:
        
