---
- hosts: windows
  name: Prueba
  become: false
  gather_facts: true
  
  tasks:
    - name: Show hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }} "
        
    - name: Version Windows
      debug:
        msg: "Hostname: {{ ansible_os_name }} "    
        
    - name: Verificar si esta instalado Firewall
      community.windows.win_firewall_rule:
        name: firewalld
        state: present
        enabled: yes
        
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present
        
    - name: Checked if yes installed W3Svc Verificar si esta instalado W3Svc
      ansible.windows.win_service:
        name: W3Svc
        state: started
    
    - name: Open port for site on the firewall
      win_firewall_rule:
        name: "iisport{{ item.port }}"
        enable: yes
        state: present
        localport: "{{ item.port }}"
        action: Allow
        direction: In
        protocol: Tcp
      with_items: "{{ iis_sites }}"   
    
     
        
