---
- hosts: windows
  name: Prueba
  become: false
  gather_facts: true
  
  tasks:
    - name: Show hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }} "
        
    - name: Version Windows
      debug:
        msg: "Hostname: {{ ansible_os_name }} "    
        
    - name: Verificar si esta instalado Firewall
      ansible.windows.win_feature:
        name: 
        - Firewall
        - W3Svc
        state: present
        
