---
- hosts: windows
  name: Prueba
  become: false
  gather_facts: true
  
  tasks:
    - name: Show hostname
      debug:
        msg: " Hostname: {{ ansible_hostname }} "
        
    - name: Version Windows
      debug:
        msg: " OS version: {{ ansible_os_name }} "    
        
    - name: Verificar si esta instalado Firewall
      community.windows.win_firewall_rule:
        name: firewalld
        state: present
        enabled: yes
        
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present
        
    - name: Checked if yes installed W3Svc Verificar si esta instalado W3Svc
      ansible.windows.win_service:
        name: W3Svc
        state: started
    
      
    - name: Create directory structure
      ansible.windows.win_file:
        path: C:\Temp\reto1
        state: directory
        
    - name: Touch a file (creates if not present, updates modification time if present)
      ansible.windows.win_file:
        path: C:\Temp\reto1\reto1_content
        state: touch
        
    - name: Set the contents of a file
      ansible.windows.win_copy:
        content: " OS version: {{ ansible_os_name }} " 
        dest: C:\Temp\reto1\reto1_content
    
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        
    - name: Reboot the machine with all defaults
      ansible.windows.win_reboot:
    
    - name: Change the hostname to marcoparco
      ansible.windows.win_hostname:
        name: marcoparco
      register: res
      
    - name: Copy a single file, but keep a backup
      ansible.windows.win_copy:
        src: C:\Temp\reto1\reto1_content
        dest: C:\Temp\reto1\backupreto1_content
        remote_src: yes
        backup: yes
        
        
    - name: Add a line to a file and ensure the resulting file uses unix line separators
      community.windows.win_lineinfile:
        path: C:\Temp\reto1\reto1_content
        line: ESTA ES UNA PRUEBA
        newline: unix
        
    - name: Add a line to a file and ensure the resulting file uses unix line separators
      community.windows.win_lineinfile:
        path: C:\Temp\reto1\reto1_content
        regex: '^OS version: Microsoft Windows Server 2019 Datacenter'
        line: 'OS version: Microsoft Windows Server 2019 Datacenter=ANSIBLE CON WINDOWS'
    
